
name: Deploy - Staging
on:
  push:
    branches:
      - main
  workflow_dispatch:
    name: 'Deploy - BE'

jobs:
  test:
  runs-on: ubuntu-latest
    steps:
      - name: service 1
        run: echo "service 1 deployed"
