
name: DeployClient
on:
  push:
    branches:
      - main
    paths:
      - server
  workflow_run:
    workflows: ['DeployServer']
    paths:
      - server
    types:
      - completed
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: service 1
        run: echo "service 1 deployed"
