name: DeployPreview
on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: check for file changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            backend:
              - 'server/**'
            frontend:
              - 'client/**'
      - name: backend deployment
        if: steps.changes.outputs.backend == 'true'
        id: backendDeployment
        run: |
          echo 'backend deployment'
          echo "::set-output name=url::https://generated-api.example.com"
      - name: client deployment
        if: steps.changes.outputs.frontend == 'true' || steps.changes.outputs.backend == 'true'
        run: |
          echo 'frontend deployment with url ${steps.backendDeployment.outputs.url||secrets.URL}'



